package mazeGenerator;

import java.io.Serializable;

/**
 * This class represents any exceptions generated by the warehouse
 * simulation.  If you find that the parameters provided to your
 * methods are invalid then you should throw a new instance of
 * this class.
 * @author Group300
 * @version 1.0
 */
 public class MazeGeneratorException extends Exception implements Serializable {

    /**
     * Creates a new instance of MazeGeneratorException.
     *
     * @param message an informative message about the problem found
     */
    public MazeGeneratorException(String message) { super("Maze Generator Exception: " + message);
    }
}
